Inventory/Controllers/LoginsController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Inventory.Controllers
{
    public class LoginsController : Controller
    {
        private InventoryDBEntities db = new InventoryDBEntities();

        // GET: Logins
        public ActionResult Index()
        {
            return View(new Login());
        }

        // POST: Logins
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Login u)
        {
            var user = db.Logins.FirstOrDefault(l => l.UserName == u.UserName && l.Password == u.Password);
            if (user != null)
            {
                Session["name"] = u.UserName;
                return RedirectToAction("Main");
            }

            ModelState.AddModelError("", "Invalid username or password.");
            return View(u);
        }

        public ActionResult Logout()
        {
            Session.Remove("name");
            return RedirectToAction("Index");
        }

        public ActionResult Main()
        {
            if (Session["name"] == null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inventory Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Inventory/Views/Shared/_sidepanelLayoutPage.cshtml
@using System.Web.Mvc.Html;
@using System.Web.Mvc;


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Inventory</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
  
</head>
<body>
    @if (Session["name"] != null)
    {
        <div class="d-flex">
            <nav id="sidebar" class="bg-dark text-white p-4" style="width: 250px;">
                <h4>Welcome, @Session["name"]</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Main", "Logins")">Main</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="@Url.Action("Logout", "Logins")">Logout</a>
                    </li>
                </ul>
            </nav>
            <div class="content p-4" style="margin-left: 250px;">
                @RenderBody()
            </div>
        </div>
    }
    else
    {
        @RenderBody()
    }

    @RenderSection("Scripts", required: false)
</body>
</html>